pipelines: 
  - name: pipelines_state_test
    configuration:
      runtime:       
        type: image
        image:
          custom:
            name: "pipelines-docker.jfrog.io/jfrog/pipelines-u16node"
            tag: "8.16.0-b1763"
    steps:
      - name: pipe_state
        type: Bash
        execution:
          onStart:
            - restore_pipeline_files pipeline_state_file pipeline_state.txt
          onExecute:
            - sleep 10m
            - echo "Good Buoy!!!"
            - node --version
