pipelines: 
  - name: pipelines_state_test
    configuration:
      runtime:       
        type: image
        image:
          auto:
            language: "nodejs"
            versions:
              - 8.16.0
    steps:
      - name: pipe_state
        type: Bash
        execution:
          onStart:
            - restore_pipeline_files pipeline_state_file pipeline_state.txt
          onExecute:
            - echo "Good Buoy!!!"
            - node --version
