    
resources:
  - name: gitResource
    type: GitRepo
    configuration:
      gitProvider: github_kirti
      path: kirtisahu05/ymlTest
  - name: RemoteFile
    type: RemoteFile
    configuration:
      source: artifactoryIntegration
      fileLocation: 'https://github.com/kirtisahu05/ymlTest/edit/master/pipelines.yml'
      fileName: 'pipelines.yml'
      fileDateTime: 'dttm'
  - name: KubeCluster
    type: KubeCluster
    configuration:
      kubernetesConfig: kub_kirti
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKey_kirti
  - name: Webhook
    type: Webhook
    configuration:
      webhookName: webhookIntegration
      payload: 'asd123'
  - name: DistributionRule
    type: DistributionRule
    configuration:
      sourceArtifactory: artifactoryIntegration     
      serviceName: citySer
      siteName: jp
      cityName: blr
      countryCodes:
        - cc1
        - cc2
  - name: FileSpec
    type: FileSpec
    configuration:      
      sourceArtifactory: docker_kirti
      pattern: 'test'
      aql: 'test'
      target: 'test'
      props: 'test'
      recursive: false
#       flat: true
      excludePatterns: 'test'
      archiveEntries: 'test'
      sortBy: 'test'
      sortOrder: 'test'
      limit: 1
      offset: 1
  - name: Aql
    type: Aql
    configuration:
      sourceArtifactory: artifactoryIntegration
      query: 'asd'
  - name: BuildInfo 
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 123
pipelines:
  - name: img_test_pipeline
    steps:
      - name: Bash_1
        type: Bash
        configuration:
          affinityGroup: bldGroup 
          priority: 0
          outputResources:
            - name: BuildInfo
        execution:
          onExecute:
            - write_output DockerTagTest "imageTag="$step_id
      - name: Bash_2
        type: Bash
        configuration:
          affinityGroup: bldGroup 
          priority: 0
          inputResources:
            - name: BuildInfo
            - name: Aql
            - name: Webhook
            - name: DistributionRule
            - name: KubeCluster
        execution:
          onExecute:
            - echo "done"
      - name: Bash_3
        type: Bash
        configuration:
          affinityGroup: bldGroup
          priority: 0
          inputSteps:
            - name: Bash_2
          inputResources:
            - name: FileSpec
            - name: RemoteFile
          integrations:
            - name: artifactoryIntegration
            - name: github_kirti
        execution:
          onExecute:
            - echo "done"
      - name: Bash_4
        type: Bash
        configuration:
          affinityGroup: bldGroup
          priority: 0
          inputSteps:
            - name: Bash_3
        execution:
          onExecute:
            - echo "done"
      - name: Bash_5
        type: Bash
        configuration:
          affinityGroup: bldGroup
          priority: 0
          inputSteps:
            - name: Bash_4
        execution:
          onExecute:
            - echo "done"
      - name: Bash_6
        type: Bash
        configuration:
          affinityGroup: bldGroup
          priority: 0
          inputSteps:
            - name: Bash_5
        execution:
          onExecute:
            - echo "done"
      - name: Bash_7
        type: Bash
        configuration:
          affinityGroup: bldGroup
          priority: 0
          inputSteps:
            - name: Bash_6
        execution:
          onExecute:
            - echo "done"
#       - name: bash
#         type: bash
#         execution:
#           onExecute:
#             - echo "executing..."
#         triggeredBy:
#           resources:
#             - KubeCluster
#             - RemoteFile
#             - FileSpec
#       - name: CreateReleaseBundle
#         type: CreateReleaseBundle
#         configuration:
#           releaseBundleName: 'test'
#           releaseBundleVersion: 'test'
#           dryRun: false
#           sign: false
#           storeAtSourceArtifactory: 'test'
#           description: 'test'
#           releaseNotes:
#             content: 'test'
#             syntax: plain_text
#           inputResources:
#             - name: KubeCluster
#             - name: BuildInfo
#           inputSteps:
#             - name: bash
#           integrations:
#             - name: artifactoryIntegration
#           outputResources:
#             - name: RemoteFile
